version: 2

project_name: opentelemetry-collector-nats

before:
  hooks:
    - helm lint deploy/helm/opentelemetry-collector-nats
    - helm package deploy/helm/opentelemetry-collector-nats --app-version {{ .Version }} --version {{ .Version }} -d deploy/helm

publishers:
  - name: helm
    cmd: helm push deploy/helm/opentelemetry-collector-nats-{{ .Version }}.tgz oci://ghcr.io/mikluko/opentelemetry-collector-nats/helm

builds:
  - id: collector
    main: ./cmd/opentelemetry-collector-nats
    binary: opentelemetry-collector-nats
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

release:
  github:
    owner: mikluko
    name: opentelemetry-collector-nats
  draft: true
  prerelease: auto
  extra_files:
    - glob: deploy/helm/opentelemetry-collector-nats-{{ .Version }}.tgz
