version: 2

project_name: opentelemetry-collector-nats

before:
  hooks:
    - go mod tidy
    # Update Helm chart version and package
    - >-
      sed -i.bak
      -e 's/^version:.*/version: {{ .Version }}/'
      -e 's/^appVersion:.*/appVersion: "{{ .Version }}"/'
      deploy/helm/opentelemetry-collector-nats/Chart.yaml
    - helm package deploy/helm/opentelemetry-collector-nats -d dist/

builds:
  - id: collector
    main: ./cmd/opentelemetry-collector-nats
    binary: opentelemetry-collector-nats
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

release:
  github:
    owner: mikluko
    name: opentelemetry-collector-nats
  draft: false
  prerelease: auto
  extra_files:
    - glob: dist/opentelemetry-collector-nats-*.tgz
